apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  labels:
    app: local
spec:
  capacity:
    storage: 200Mi # 200 mb of storage
  accessModes:
    - ReadWriteMany # Can be mounted as read-write by a single node 
  storageClassName: local-storage
  hostPath:
   path : "/mnt/data" # Path on the host where the volume is stored