apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-init
spec:
  initContainers:
    - name: init-myservice
      image: busybox:latest
      command: ['/bin/sh', "-c", "mkdir -p /info/message && echo 'Initialization complete' > /info/message/status.txt"]
      volumeMounts:
        - name: info-volume
          mountPath: /info

  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: info-volume
          mountPath: /info  # Mounting the volume to a path inside nginx container 
  volumes:
    - name: info-volume # Defining the volume
      emptyDir: {}      # emptyDir volume to share data between initContainer and main container  