apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-sidecar
spec:
  containers:
    - name: nginx    # Main application container
      image: nginx:latest
      volumeMounts:
        - name: log-volume   # Mounting the volume to share logs
          mountPath: /var/log/nginx  # Path where nginx stores its logs
      ports:
        - containerPort: 80

    - name: nginx-log-container   # Sidecar container which will run some shell scripts
      image: busybox:latest
      command: ['/bin/sh', '-c', 'tail -f /var/log/nginx/access.log']  # tail command is used to read the log file and -c for command
      volumeMounts: 
        - name: log-volume          # Mounting the same volume to access logs
          mountPath: /var/log/nginx   # Path where nginx stores its logs

  volumes:  
    - name: log-volume   # name of the volume
      emptyDir: {}      # emptyDir volume to share logs between main and sidecar container