apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - port: 27017           # Port inside the cluster
      targetPort: 27017     # Port on the MongoDB container
      nodePort: 30017       # Port exposed on the node (range: 30000–32767)